// Generated by CoffeeScript 1.3.3
(function() {
  var logger, winston;

  winston = require("winston");

  logger = new winston.Logger({
    exitOnError: false,
    transports: [new winston.transports.Console()]
  });

  module.exports = logger;

}).call(this);
