// Generated by CoffeeScript 1.3.3
(function() {
  var World, app, express, io;

  express = require("express");

  app = express.createServer();

  io = require("socket.io").listen(app);

  app.use(express["static"]("" + __dirname + "/../web"));

  World = new (require("./classes/world"));

  World.generate(50, 50);

  io.sockets.on("connection", function(socket) {
    return socket.emit("view", World.simplify());
  });

  app.listen(8088);

}).call(this);
