// Generated by CoffeeScript 1.3.3
(function() {
  var Player, app, express, io, logger, port, world;

  express = require("express");

  app = express.createServer();

  io = require("socket.io").listen(app);

  logger = require("./logger");

  app.use(express["static"]("" + __dirname + "/../web"));

  world = new (require("./classes/world"));

  world.generate(50, 50);

  Player = require("./classes/player");

  io.set('log level', 1);

  io.sockets.on("connection", function(socket) {
    var player;
    world.add(player = socket.player = new Player());
    return player.setSocket(socket);
  });

  port = process.env.PORT || 8088;

  app.listen(port);

  console.log("App listening on " + port);

}).call(this);
