// Generated by CoffeeScript 1.3.3
(function() {
  var Action, Base, Give, Take,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("../classes/base");

  Action = (function(_super) {

    __extends(Action, _super);

    function Action() {
      return Action.__super__.constructor.apply(this, arguments);
    }

    Action.prototype["do"] = function() {};

    Action.prototype.reactions = {};

    return Action;

  })(Base);

  Give = (function(_super) {

    __extends(Give, _super);

    function Give() {
      return Give.__super__.constructor.apply(this, arguments);
    }

    Give.prototype.defaults = {
      what: [],
      max: 0,
      min: 0,
      howMuch: []
    };

    Give.prototype.reactions = {
      "give": function(_arg) {
        var amount, item, what, _results;
        what = _arg.what;
        _results = [];
        for (item in what) {
          amount = what[item];
          _results.push(this.entity[item] += amount);
        }
        return _results;
      }
    };

    return Give;

  })(Action);

  Take = (function(_super) {

    __extends(Take, _super);

    function Take() {
      return Take.__super__.constructor.apply(this, arguments);
    }

    Take.prototype.defaults = {
      what: {},
      distance: 0
    };

    Take.prototype["do"] = function() {
      var entity, location, _ref, _results;
      _ref = this.entity.map;
      _results = [];
      for (location in _ref) {
        entity = _ref[location];
        if (entity != null) {
          if (entity.id !== this.entity.id) {
            _results.push(entity.emit("take", {
              what: this.what,
              who: this.entity
            }));
          } else {
            _results.push(void 0);
          }
        }
      }
      return _results;
    };

    Take.prototype.reactions = {
      "take": function(_arg) {
        var amount, item, what, whatToGive, who;
        what = _arg.what, who = _arg.who;
        whatToGive = {};
        for (item in what) {
          amount = what[item];
          if (this.entity[item] && this.entity[item] > 0) {
            if (this.entity[item] <= amount) {
              amount = this.entity[item];
            }
            this.entity[item] -= amount;
            whatToGive[item] = amount;
          }
        }
        return who.emit("give", {
          what: whatToGive,
          who: this.entity
        });
      }
    };

    return Take;

  })(Action);

  module.exports = {
    Take: Take,
    Action: Action,
    Give: Give
  };

}).call(this);
