// Generated by CoffeeScript 1.4.0
(function() {
  var Entity, World, assert, util, vows;

  vows = require("vows");

  assert = require("assert");

  util = require("util");

  Entity = require("../server/classes/entity");

  World = require("../server/classes/world");

  vows.describe("Actions").addBatch({
    "Take and Give": {
      topic: function() {
        var giver, taker, world,
          _this = this;
        world = new World();
        world.add(giver = new Entity().load({
          properties: {
            test: 5,
            test2: 1,
            name: "giver",
            x: 0,
            y: 0,
            z: 0
          },
          goals: [
            {
              name: "give tests",
              reactions: [
                {
                  type: "take"
                }
              ]
            }
          ]
        }));
        world.add(taker = new Entity().load({
          properties: {
            test: 0,
            test2: 0,
            name: "taker",
            x: 0,
            y: 0,
            z: 1
          },
          view: 1,
          goals: [
            {
              name: "take tests",
              actions: [
                {
                  type: "take",
                  what: {
                    test: 1,
                    test2: 1
                  }
                }
              ],
              reactions: [
                {
                  type: "give"
                }
              ]
            }
          ]
        }));
        taker.on("change:test", function() {
          return _this.callback(giver, taker);
        });
        taker.goals[0].execute();
      },
      "taker has taken": function(giver, taker) {
        return assert.equal(taker.test, 1);
      },
      "giver has given": function(giver, taker) {
        return assert.equal(giver.test, 4);
      }
    }
  })["export"](module);

}).call(this);
