// Generated by CoffeeScript 1.3.3
(function() {
  var Entity, World, assert, util, vows;

  vows = require("vows");

  assert = require("assert");

  util = require("util");

  Entity = require("../server/classes/Entity");

  World = require("../server/classes/World");

  vows.describe("Entity").addBatch({
    "An Entity": {
      topic: new Entity(),
      "has default properties": function(entity) {
        return assert.equal(entity.x, 0);
      },
      "has change events": {
        topic: function(entity) {
          var _this = this;
          entity.once("change:x", function(_arg) {
            var value;
            value = _arg.value;
            return _this.callback(null, value);
          });
          entity.x = 1;
        },
        "that fire when property is changed": function(value) {
          return assert.equal(value, 1);
        }
      },
      "has bindings": function(entity) {
        return assert.deepEqual(entity.location, [1, 0, 0]);
      },
      "has binding change events": {
        topic: function(entity) {
          var _this = this;
          entity.once("change:location", function(_arg) {
            var value;
            value = _arg.value;
            return _this.callback(null, value);
          });
          entity.x = 5;
        },
        "that fire when a binding is changed": function(value) {
          return assert.deepEqual(value, [5, 0, 0]);
        }
      },
      "has children": function(entity) {
        return assert.isArray(entity.children);
      },
      "can add children": {
        topic: function(entity) {
          var child;
          child = new Entity();
          entity.add(child);
          return [entity, child];
        },
        "that are present": function(_arg) {
          var child, entity;
          entity = _arg[0], child = _arg[1];
          return assert.equal(entity.children[0], child);
        },
        "that can be removed": function(_arg) {
          var child, entity;
          entity = _arg[0], child = _arg[1];
          entity.remove(child);
          return assert.equal(entity.children.length, 0);
        }
      },
      "can simplify": {
        topic: new Entity({
          id: "foo",
          x: 1
        }),
        "with no children": function(entity) {
          return assert.deepEqual(entity.simplify(), {
            properties: {
              x: 1,
              y: 0,
              z: 0,
              id: "foo"
            },
            children: []
          });
        },
        "with children": function(entity) {
          var child;
          child = new Entity();
          entity.add(child);
          return assert.deepEqual(entity.simplify(), {
            properties: {
              x: 1,
              y: 0,
              z: 0,
              id: "foo"
            },
            children: [child.simplify()]
          });
        }
      },
      "has a map": function(entity) {
        return assert.isObject(entity.map);
      },
      "handles view changes": {
        topic: function() {
          var e1, e2, world,
            _this = this;
          world = new World();
          world.add(e1 = new Entity({
            x: 0,
            y: 0,
            z: 0,
            id: "e1"
          }));
          e1.setView(1);
          e1.once("change:view", function(_arg) {
            var entity, location;
            location = _arg.location, entity = _arg.entity;
            return _this.callback(null, location, entity, e1);
          });
          world.add(e2 = new Entity({
            x: 1,
            y: 0,
            z: 0,
            id: "e2"
          }));
        },
        "when an entity is added": function(error, location, entity) {
          assert.equal(entity.id, "e2");
          return assert.deepEqual(entity.location, location);
        },
        "its map is also updated": function(error, location, entity, e1) {
          return assert.equal(e1.map[location.join(":")].id, entity.id);
        },
        "when an entity moves": {
          topic: function(location, e2, e1) {
            var _this = this;
            e1.once("change:view", function(_arg) {
              var entity, location;
              location = _arg.location, entity = _arg.entity;
              return _this.callback(null, location, entity, e1);
            });
            e2.move([1, 0, 1]);
          },
          "its view is updated": function(error, location, e2, e1) {
            return assert.equal(e1.map["1:0:1"].id, e2.id);
          },
          "and the old location is cleared": function(error, location, e2, e1) {
            return assert.equal(e1.map["1:0:0"], void 0);
          }
        }
      }
    }
  })["export"](module);

}).call(this);
