// Generated by CoffeeScript 1.4.0
(function() {
  var Entities, World, assert, vows;

  vows = require("vows");

  assert = require("assert");

  Entities = require("../server/entities");

  World = require("../server/classes/world");

  vows.describe("Entities").addBatch({
    "Entities": {
      topic: Entities,
      "have classes from data": function(entities) {
        return assert.notEqual(Object.keys(entities).length, 0);
      },
      "has test entity": function(entities) {
        return assert(entities.Test !== null, "is not null");
      },
      "can be instantied": function(entities) {
        return new entities.Test();
      }
    },
    "Tree and Land": {
      topic: function() {
        var land, tree, trigger, world,
          _this = this;
        tree = new Entities.Tree({
          x: 0,
          y: 0,
          z: 1
        });
        land = new Entities.Land({
          x: 0,
          y: 0,
          z: 0
        });
        trigger = tree.goals[0].triggers[0];
        trigger.min = 1;
        trigger.max = 1;
        tree.goals[0].start();
        tree.once("change:phosphorus", function() {
          return _this.callback(tree, land);
        });
        world = new World();
        world.add(tree);
        world.add(land);
      },
      "tree has eaten": function(tree, land) {
        return assert.equal(tree.phosphorus, 11);
      }
    }
  })["export"](module);

}).call(this);
