// Generated by CoffeeScript 1.3.3
(function() {
  var Entities, assert, vows;

  vows = require("vows");

  assert = require("assert");

  Entities = require("../server/entities");

  vows.describe("Entities").addBatch({
    "Entities": {
      topic: Entities,
      "have classes from data": function(entities) {
        return assert.notEqual(Object.keys(entities).length, 0);
      },
      "has test entity": function(entities) {
        return assert(entities.test !== void 0, "is not null");
      },
      "can be instantied": function(entities) {
        return new entities.test();
      }
    }
  })["export"](module);

}).call(this);
