// Generated by CoffeeScript 1.3.3
(function() {
  var Goal, assert, vows;

  vows = require("vows");

  assert = require("assert");

  Goal = require("../server/classes/Goal");

  vows.describe("Goal").addBatch({
    "A Goal": {
      topic: new Goal(),
      "has an area": function(goal) {
        assert.deepEqual(goal.area[0], [0, 0, 0]);
        return assert.deepEqual(goal.area[1], [0, 1, 0]);
      }
    }
  });

}).call(this);
