// Generated by CoffeeScript 1.4.0
(function() {
  var Land, assert, vows;

  vows = require("vows");

  assert = require("assert");

  Land = require("../server/classes/Land");

  vows.describe("Land").addBatch({
    "A Land": {
      topic: new Land(),
      "has nutrients": function(land) {
        assert.isNumber(land.phosphorus);
        assert.isNumber(land.potassium);
        return assert.isNumber(land.nitrogen);
      },
      "can eat": {
        topic: function(land) {
          var otherLand,
            _this = this;
          otherLand = new Land();
          otherLand.nitrogen = 0;
          land.nitrogen = 5;
          otherLand.on("feed", function() {
            return _this.callback(null, [land, otherLand]);
          });
          land.emit("eat", {
            what: "nitrogen",
            howMuch: 5,
            who: otherLand
          });
        },
        "has fed the other land": function(_arg) {
          var land, otherLand;
          land = _arg[0], otherLand = _arg[1];
          return assert.equal(land.nitrogen, 0);
        },
        "has eaten from land": function(_arg) {
          var land, otherLand;
          land = _arg[0], otherLand = _arg[1];
          return assert.equal(otherLand.nitrogen, 5);
        }
      }
    }
  })["export"](module);

}).call(this);
