// Generated by CoffeeScript 1.4.0
(function() {
  var Base, EventEmitter, uuid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require("events").EventEmitter;

  uuid = require("node-uuid");

  /*
      Basic Entity class
  */


  Base = (function(_super) {

    __extends(Base, _super);

    function Base(overrides) {
      var name, value;
      if (overrides == null) {
        overrides = {};
      }
      this.children = [];
      this.properties = {};
      this.privates = {};
      this.handleSupers(this.constructor, this.sets, "defaults");
      this.sets(this.defaults);
      this.handleSupers(this.constructor, this.sets, "privates", this.privates);
      this.sets(this.privates);
      this.set("id", uuid.v4());
      this.handleSupers(this.constructor, this.setBindings, "bindings");
      this.setBindings(this.bindings);
      this.init();
      for (name in overrides) {
        value = overrides[name];
        this[name] = value;
      }
      this.setMaxListeners(0);
      this.handleSupers(this.constructor, this.setEvents, "events");
      this.setEvents(this.events);
    }

    Base.prototype.handleSupers = function(level, fn, prop, additional) {
      if (level.__super__[prop]) {
        fn.call(this, level.__super__[prop], additional);
        return this.handleSupers(level.__super__.constructor, fn, prop, additional);
      }
    };

    Base.prototype.init = function() {};

    Base.prototype.sets = function(values, container) {
      var name, value, _results;
      if (container == null) {
        container = this.properties;
      }
      _results = [];
      for (name in values) {
        value = values[name];
        _results.push(this.set(name, value, container));
      }
      return _results;
    };

    Base.prototype.set = function(name, value, container) {
      if (container == null) {
        container = this.properties;
      }
      container[name] = value;
      if (!this.__lookupGetter__(name)) {
        this.__defineGetter__(name, function() {
          return container[name];
        });
        return this.__defineSetter__(name, function(val) {
          var oldProp;
          oldProp = container[name];
          container[name] = val;
          this.emit("change", {
            name: name,
            value: val,
            oldValue: oldProp,
            dif: oldProp - value
          });
          return this.emit("change:" + name, {
            value: val,
            oldValue: oldProp,
            dif: oldProp - value
          });
        });
      }
    };

    Base.prototype.mapSimplify = function() {
      var entity, location, view, _ref;
      view = [];
      _ref = this.map;
      for (location in _ref) {
        entity = _ref[location];
        if (entity) {
          view.push(entity.simplify());
        }
      }
      return view;
    };

    Base.prototype.simplify = function() {
      var child, simple, _i, _len, _ref;
      simple = {
        children: [],
        properties: this.properties
      };
      _ref = this.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        simple.children.push(child.simplify());
      }
      return simple;
    };

    Base.prototype.toJSON = function(recurse) {
      if (recurse) {
        return JSON.stringify(this.simplify());
      } else {
        return JSON.stringify(this.properties);
      }
    };

    Base.prototype.add = function(child) {
      this.children.push(child);
      child.parent = this;
      child.emit("added", {
        entity: this
      });
      return this.emit("add", {
        entity: child
      });
    };

    Base.prototype.remove = function(child) {
      var location;
      location = this.children.indexOf(child);
      if (location !== -1) {
        this.children.splice(location, 1);
        child.parent = void 0;
        this.emit("remove", {
          entity: child
        });
        return child.emit("removed", {
          entity: this
        });
      }
    };

    Base.prototype.setEvents = function(events) {
      var event, handler, _results;
      _results = [];
      for (event in events) {
        handler = events[event];
        if (typeof handler === "function") {
          _results.push(this.on(event, handler));
        } else if (typeof handler === "string") {
          _results.push(this.on(event, this[handler]));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Base.prototype.setBindings = function(bindings) {
      var binding, values, _results,
        _this = this;
      _results = [];
      for (binding in bindings) {
        values = bindings[binding];
        _results.push((function(binding, values) {
          var bind, prop, _i, _len, _results1;
          _this.__defineGetter__(_this.properties[binding], function() {
            return _this[binding];
          });
          if (typeof values === "string") {
            bind = values.split(" ");
            _this.__defineGetter__(binding, function() {
              return this[bind[0]][bind[1]];
            });
            _this.__defineSetter__(binding, function(value) {
              this[bind[0]][bind[1]] = value;
              this.emit("change:" + binding, {
                value: value
              });
              return this.emit("change:" + bind[0], {
                value: this[bind[0]]
              });
            });
            return _this.on("change:" + bind[0], function(_arg) {
              var oldValue, value;
              value = _arg.value, oldValue = _arg.oldValue;
              if (!oldValue || value[bind[1]] !== oldValue[bind[1]]) {
                return this.emit("change:" + binding, {
                  value: value,
                  oldValue: oldValue[bind[1]],
                  dif: oldValue[bind[1]] - value
                });
              }
            });
          } else {
            _this.__defineGetter__(binding, function() {
              var prop, ret, _i, _len;
              ret = [];
              for (_i = 0, _len = values.length; _i < _len; _i++) {
                prop = values[_i];
                ret.push(this[prop]);
              }
              return ret;
            });
            _this.__defineSetter__(binding, function(value) {
              var i, prop, _i, _len, _results1;
              _results1 = [];
              for (i = _i = 0, _len = value.length; _i < _len; i = ++_i) {
                prop = value[i];
                if (this[values[i]] !== prop) {
                  _results1.push(this[values[i]] = prop);
                } else {
                  _results1.push(void 0);
                }
              }
              return _results1;
            });
            _results1 = [];
            for (_i = 0, _len = values.length; _i < _len; _i++) {
              prop = values[_i];
              _results1.push((function(binding, prop) {
                return _this.on("change:" + prop, function(_arg) {
                  var value;
                  value = _arg.value;
                  return this.emit("change:" + binding, {
                    value: this[binding]
                  });
                });
              })(binding, prop));
            }
            return _results1;
          }
        })(binding, values));
      }
      return _results;
    };

    return Base;

  })(EventEmitter);

  module.exports = Base;

}).call(this);
