// Generated by CoffeeScript 1.3.3
(function() {
  var Entity, Land, Tree, World,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require("./entity");

  Land = require("./land");

  Tree = require("./tree");

  /*
      The world object + persistence
  */


  World = (function(_super) {

    __extends(World, _super);

    function World() {
      return World.__super__.constructor.apply(this, arguments);
    }

    World.prototype.init = function() {
      return this.locations = {};
    };

    World.prototype.generate = function(w, h) {
      var t, x, y, _i, _j, _k, _results;
      for (x = _i = 0; 0 <= w ? _i <= w : _i >= w; x = 0 <= w ? ++_i : --_i) {
        for (y = _j = 0; 0 <= h ? _j <= h : _j >= h; y = 0 <= h ? ++_j : --_j) {
          this.add(new Land({
            x: x,
            y: y
          }, this));
        }
      }
      _results = [];
      for (t = _k = 0; _k <= 10; t = ++_k) {
        _results.push(this.add(new Tree({
          x: Math.floor(Math.random() * w),
          y: Math.floor(Math.random() * h),
          z: 1
        })));
      }
      return _results;
    };

    World.prototype.loc = function(event, fn) {
      this.on.apply(this, arguments);
      if (this.locations[event]) {
        return fn(this.locations[event].location, this.locations[event]);
      }
    };

    World.prototype.move = function(entity, location) {
      var dest, sLoc;
      sLoc = location.join(":");
      dest = this.locations[sLoc];
      if (!dest) {
        this.locations[sLoc] = entity;
        this.emit(sLoc, location, entity);
        return entity.emit("moved", location);
      } else {
        entity.emit("collision", dest, location);
        return dest.emit("collision", entity, location);
      }
    };

    return World;

  })(Entity);

  module.exports = World;

}).call(this);
